### ISSUE TITLE
Is it possible to use Doppler in an Apache2 environment

### ISSUE THREAD

**Issue by PsclDev** [EnKrypt/Doppler#6]
Is it possible to run Doppler in an Apache2 environment to access the site by domain and protect it with a password?

Also I have the question, how can I start Doppler, that this stays open and doesn't close again (This question might be due to my fresh knowledge of Debian)

Thanks for the great tool and your answer in advance
-Pascal

**Comment by EnKrypt** [comment]
Yes, so you will have to set up a reverse proxy in Apache to do that since Doppler is self served.

For your second question, you will have to write a systemd service. You can set the restart policy such that it always auto-restarts in case of a crash.

I suggest looking both of these up if you're unsure or don't have much experience with either.

Good luck! Update us with how it goes.

**Comment by PsclDev** [comment]
Thanks for your answer, I was able to successfully set up a proxy and create a system service. 

I don't know how active the project is still, but would it be a good idea to add a password in the future, so that not everyone who knows the link can see the data? For example with a parameter like port or interval

Or is it also possible to secure this via .htaccess with a password?

Stay safe
-UnRunDead

**Comment by EnKrypt** [comment]
I think that's a really good idea. Having an optional flag for a password is a good feature to have. Thanks a lot for the suggestion.

I'm a bit scrapped on free time at the moment, but this is something I think we should be able to pick up next. Check back in around a month or so. Of course, feel free to help out and contribute yourself as well.

In the meantime, I think you should be able to secure it within Apache anyway. You won't be able to use a .htaccess file on a reverse proxy, because there's nowhere to put that file, however you should still be able to set up auth for it within the Apache config.

[See this stackoverflow question](https://stackoverflow.com/questions/5011102/apache-reverse-proxy-with-basic-authentication)
